development:
  adapter: sqlite3
  encoding: unicode
  database: databaseandrii
  pool: 5
  username: andrii
  password:
  timeout: 5000
 
test:
  adapter: sqlite3
  encoding: unicode
  database: testdatabaseandrii
  pool: 5
  username: andrii
  password:
  timeout: 5000
 
production:
  adapter: postgresql
  encoding: unicode
  database: productiondatabaseandrii
  pool: 5
  username: andrii
  password:
  timeout: 5000